# Generated by Django 5.0.1 on 2024-02-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkingWithGit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositories',
            name='directory',
            field=models.CharField(default='D:/git_repositories', max_length=250),
        ),
    ]
