# Generated by Django 5.0.1 on 2024-02-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkingWithGit', '0003_alter_repositories_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositories',
            name='directory',
            field=models.CharField(default='D:/git_repositories', max_length=10000),
        ),
    ]
