# Generated by Django 5.0.1 on 2024-03-03 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalkingWithGit', '0005_repositories_current_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('branch_source', models.CharField(max_length=250)),
                ('branch_dest', models.CharField(max_length=250)),
                ('closed', models.BooleanField(default=False)),
                ('merge_date', models.DateField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TalkingWithGit.repositories')),
            ],
        ),
    ]
